# .github/labels.yml

# ------------------------
# Types
# ------------------------
- name: bug
  color: d73a4a
  description: Something isn’t working as intended

- name: crash
  color: b60205
  description: Causes the application or process to terminate unexpectedly

- name: feature
  color: 0e8a16
  description: A new capability or major functionality

- name: enhancement
  color: a2eeef
  description: An improvement to existing functionality

- name: documentation
  color: 0075ca
  description: Updates, additions, or fixes to documentation

- name: question
  color: d876e3
  description: A request for clarification or additional information

# ------------------------
# .github/labels.yml

# ------------------------
# Types
# ------------------------
- name: bug
  color: d73a4a
  description: Something isn’t working as intended

- name: crash
  color: b60205
  description: Causes the application or process to terminate unexpectedly

- name: feature
  color: 0e8a16
  description: A new capability or major functionality

- name: enhancement
  color: a2eeef
  description: An improvement to existing functionality

- name: documentation
  color: 0075ca
  description: Updates, additions, or fixes to documentation

- name: question
  color: d876e3
  description: A request for clarification or additional information

# ------------------------
# Priority
# ------------------------
- name: "priority: low"
  color: c2e0c6
  description: Nice to have, not time-sensitive

- name: "priority: medium"
  color: fbca04
  description: Important but not urgent

- name: "priority: high"
  color: d93f0b
  description: Requires prompt attention

- name: "priority: critical"
  color: b60205
  description: Blocking usage or causing severe issues

# ------------------------
# Platform
# ------------------------
- name: "platform: windows"
  color: 00a1f1
  description: Windows-specific

- name: "platform: linux"
  color: 000000
  description: Linux-specific

- name: "platform: macos"
  color: 8e8e8e
  description: macOS-specific

- name: "platform: cross-platform"
  color: bfd4f2
  description: Affects multiple platforms

# ------------------------
# Workflow / Status
# ------------------------
- name: "good first issue"
  color: 7057ff
  description: Beginner-friendly task

- name: "help wanted"
  color: 008672
  description: Community help requested

- name: blocked
  color: d876e3
  description: Waiting on another issue, decision, or dependency

- name: "needs review"
  color: 006b75
  description: Ready for maintainer review

- name: "in progress"
  color: cfd3d7
  description: Actively being worked on

# ------------------------
# Maintenance
# ------------------------
- name: refactor
  color: cfd3d7
  description: Code cleanup without behavior change

- name: performance
  color: fef2c0
  description: Performance improvements or regressions

- name: build
  color: 5319e7
  description: Build system or CI-related issues

- name: dependency
  color: 0366d6
  description: Dependency updates or problems

# ------------------------
# Resolution
# ------------------------
- name: duplicate
  color: c0c0c0
  description: Already reported elsewhere

- name: invalid
  color: e4e669
  description: Incomplete, incorrect, or not applicable

- name: wontfix
  color: 6a737d
  description: Will not be addressed


# ------------------------
